"""added form_template foreign key to child forms

Revision ID: 246fe1a317a1
Revises: f9f0a21641ed
Create Date: 2025-11-24 13:09:14.917783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246fe1a317a1'
down_revision: Union[str, Sequence[str], None] = 'f9f0a21641ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('form_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forms', 'form_templates', ['form_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'form_template_id')
    # ### end Alembic commands ###
