"""added missing form_template<>field_template relationship

Revision ID: 64eaea6b555d
Revises: 225fba1d7250
Create Date: 2025-11-24 13:02:50.278187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64eaea6b555d'
down_revision: Union[str, Sequence[str], None] = '225fba1d7250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
