"""minor edits to form models

Revision ID: 7c19a72d2c80
Revises: ee8c01aa2fb9
Create Date: 2025-11-24 12:45:23.485461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c19a72d2c80'
down_revision: Union[str, Sequence[str], None] = 'ee8c01aa2fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', 'PENDING', name='fieldstatus'), nullable=False),
    sa.Column('llm_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('field_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_template_id'], ['field_templates.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_submissions_id'), 'field_submissions', ['id'], unique=False)
    op.add_column('forms', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forms', 'users', ['user_id'], ['id'])
    op.add_column('messages', sa.Column('message_num', sa.Integer(), nullable=False))
    op.drop_column('messages', 'step_key')
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=False, server_default="placeholder_default"))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=False, server_default="placeholder_default"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.add_column('messages', sa.Column('step_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'message_num')
    op.drop_constraint(None, 'forms', type_='foreignkey')
    op.drop_column('forms', 'user_id')
    op.drop_index(op.f('ix_field_submissions_id'), table_name='field_submissions')
    op.drop_table('field_submissions')
    # ### end Alembic commands ###
