"""fixed form_template<>field_template relationship issues

Revision ID: f9f0a21641ed
Revises: 64eaea6b555d
Create Date: 2025-11-24 13:06:55.544318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f0a21641ed'
down_revision: Union[str, Sequence[str], None] = '64eaea6b555d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_templates', sa.Column('form_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'field_templates', 'form_templates', ['form_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_templates', type_='foreignkey')
    op.drop_column('field_templates', 'form_template_id')
    # ### end Alembic commands ###
